AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'content-type,authorization'"
      AllowOrigin: "'*'"
      AllowCredentials: "'*'"

Resources:
  ProcessLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bootstrap
      Runtime: provided.al2
      CodeUri: ./target/x86_64-unknown-linux-musl/release
      Timeout: 10
      MemorySize: 128
      Environment:
        Variables:
          HANDLER_TYPE: process
          OPENAI_API_KEY: !Ref OpenAIApiKey
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /process
            Method: post

  TokenInfoLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bootstrap
      Runtime: provided.al2
      CodeUri: ./target/x86_64-unknown-linux-musl/release/
      Timeout: 30
      MemorySize: 128
      Environment:
        Variables:
          HANDLER_TYPE: tokeninfo
          DEXTOOLS_API_KEY: !Ref DexToolsApiKey
          OPENAI_API_KEY: !Ref OpenAIApiKey
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: "/{proxy+}"
            Method: ANY

  HealthLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bootstrap
      Runtime: provided.al2
      CodeUri: ./target/x86_64-unknown-linux-musl/release
      Timeout: 5
      MemorySize: 128
      Environment:
        Variables:
          HANDLER_TYPE: health
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /health
            Method: get

  StatusLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bootstrap
      Runtime: provided.al2
      CodeUri: ./target/x86_64-unknown-linux-musl/release
      Timeout: 5
      MemorySize: 128
      Environment:
        Variables:
          HANDLER_TYPE: status
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /status
            Method: get

Parameters:
  OpenAIApiKey:
    Type: String
    Description: OpenAI API Key
  DexToolsApiKey:
    Type: String
    Description: DexTools API Key
